hr/urls.py
from django.urls import path, include

from .views import *

app_name = "hr"

urlpatterns = [
    path('the_company/', TheCompanyDetailView.as_view(), name="the_company_detail"),
    path('the_company_edit/', TheCompanyEditView.as_view(), name="the_company_edit"),
    path('the_company/bank_account_delete/<int:bank_account_id>', BankAccountDeleteView.as_view(),
         name="bank_account_delete"),

    path('user_data/', UserDataView.as_view(), name="user_data"),
    path('user_add/', UserAddView.as_view(), name="user_add"),
    path('user_update/<int:id>/', UserUpdateView.as_view(), name = "user_update"),
    path('user_delete/<str:list>', UserDeleteView.as_view(), name="user_delete"),
    path('user_cv_pdf/<int:id>/', UserCVPdfView.as_view(), name = "user_cv_pdf"),
    path('user_nda_pdf/<int:id>/', UserNDAPdfView.as_view(), name = "user_nda_pdf"),
    
    path('user_edit/<int:user_id>', UserEditView.as_view(), name="user_edit"),
    path('user/<int:user_id>', UserDetailView.as_view(), name="user_detail"),
    path('user/certification/<int:profile_id>', CertificationAddView.as_view(),name="certificatiob_add"),

    path('employee_type_add/', EmployeeTypeAddView.as_view(), name="employee_type_add"),
    path('employee_type/<int:employee_type_id>', EmployeeTypeDetailView.as_view(), name="employee_type_detail"),
    path('employee_type_edit/<int:employee_type_id>', EmployeeTypeEditView.as_view(), name="employee_type_edit"),
    path('employee_type_delete/<int:employee_type_id>', EmployeeTypeDeleteView.as_view(), name="employee_type_delete"),
    path('employee_type_data/', EmployeeTypeDataView.as_view(), name="employee_type_data"),

    path('team_add/', TeamAddView.as_view(), name="team_add"),
    path('team/<int:team_id>', TeamDetailView.as_view(), name="team_detail"),
    path('team_update/<int:id>/', TeamUpdateView.as_view(), name = "team_update"),
    path('team_edit/<int:team_id>', TeamEditView.as_view(), name="team_edit"),
    path('team_delete/<str:list>', TeamDeleteView.as_view(), name="team_delete"),
    path('team_data/', TeamDataView.as_view(), name="team_data"),

    path('department_add/', DepartmentAddView.as_view(), name="department_add"),
    path('department/<int:department_id>', DepartmentDetailView.as_view(), name="department_detail"),
    path('department_update/<int:id>/', DepartmentUpdateView.as_view(), name = "department_update"),
    path('department_edit/<int:department_id>', DepartmentEditView.as_view(), name="department_edit"),
    path('department_delete/<str:list>', DepartmentDeleteView.as_view(), name="department_delete"),
    path('department_data/', DepartmentDataView.as_view(), name="department_data"),
    
    path('education_add_in_user/', EducationAddView.as_view(), name = "education_add_in_user"),
    path('education_add_in_detail/u_<int:id>/', EducationInDetailAddView.as_view(), name = "education_add_in_detail"),
    path('education_delete/<str:list>', EducationDeleteView.as_view(), name = "education_delete"),
    
    path('additional_payment_add_in_detail/u_<int:id>/', AdditionalPaymentInDetailAddView.as_view(), name = "additional_payment_add_in_detail"),
    
    path('organization_chart_data/', OrganizationChartDataView.as_view(), name="organization_chart_data"),

    path('record/<int:record_id>', RecordDetailView.as_view(), name="record_detail"),
    path('record_data/', RecordDataView.as_view(), name="record_data"),

    path('api/', include("hr.api.urls")),
]

information/api/urls.py
from django.urls import path

from information.api.views import *

urlpatterns = [
    path('countries', CountryList.as_view(), name="countries_api"),
    path('cities', CityList.as_view(), name="cities_api"),
    path('companies', CompanyList.as_view(), name="companies_api"),
    path('companies/customers', CompanyCustomerList.as_view(), name="companies_customers_api"),
    path('companies/suppliers', CompanySupplierList.as_view(), name="companies_suppliers_api"),
    path('company/<int:pk>', CompanyAPI.as_view(), name="company_api"),
    path('contacts', ContactList.as_view(), name="contacts_api"),
    path('contact/<int:pk>', ContactAPI.as_view(), name="contact_api"),
    path('vessels', VesselList.as_view(), name="vessels_api"),
    path('vessel/<int:pk>', VesselAPI.as_view(), name="vessel_api"),

    path('vessel_info/vesselfinder/<int:imo>', VesselDataFromOuter.as_view(), name="vesselfinder_imo_api"),
]

information/urls.py
from django.urls import path, include

from . import views
from .views import *

app_name = "information"

urlpatterns = [
    path('company_add/', CompanyAddView.as_view(), name="company_add"),
    path('company/<int:company_id>', CompanyDetailView.as_view(), name="company_detail"),
    path('company_edit/<int:company_id>', CompanyEditView.as_view(), name="company_edit"),
    path('company_delete/<int:company_id>', CompanyDeleteView.as_view(), name="company_delete"),

    path('contact_add/', ContactAddView.as_view(), name="contact_add"),
    path('contact/<int:contact_id>', ContactDetailView.as_view(), name="contact_detail"),
    path('contact_edit/<int:contact_id>', ContactEditView.as_view(), name="contact_edit"),
    path('contact_delete/<int:contact_id>', ContactDeleteView.as_view(), name="contact_delete"),
    path('contact_remove/<int:contact_id>/company/<int:company_id>', ContactRemoveView.as_view(),
         name="contact_remove"),

    path('vessel_add/', VesselAddView.as_view(), name="vessel_add"),
    path('vessel/<int:vessel_id>', VesselDetailView.as_view(), name="vessel_detail"),
    path('vessel_edit/<int:vessel_id>', VesselEditView.as_view(), name="vessel_edit"),
    path('vessel_delete/<int:vessel_id>', VesselDeleteView.as_view(), name="vessel_delete"),
    path('vessel_remove/<int:vessel_id>', VesselRemoveView.as_view(), name="vessel_remove"),

    path('customer_data/', CustomerDataView.as_view(), name="customer_data"),
    path('supplier_data/', SupplierDataView.as_view(), name="supplier_data"),
    path('vessel_data/', VesselDataView.as_view(), name="vessel_data"),
    path('contact_person_data/', ContactDataView.as_view(), name="contact_person_data"),

    path('api/', include("information.api.urls")),
]

user/urls.py
from django.contrib.auth.views import LogoutView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path, include

from .views import *

app_name = "user"

urlpatterns = [
    path('', DashboardView.as_view(), name="dashboard"),
    path('landing/', LandingPageView.as_view(), name="landing_page"),
    path('user/profile/', ProfileView.as_view(), name="profile_page"),
    path('profile/<str:username>/', UserProfileView.as_view(), name="user_profile"),
    path('source_company_update/', SourceCompanyUpdateView.as_view(), name="source_company_update"),
    path('light_theme_update/', LightThemeUpdateView.as_view(), name="light_theme_update"),
    path('dark_theme_update/', DarkThemeUpdateView.as_view(), name="dark_theme_update"),
    path('card_color_update/', CardColorUpdateView.as_view(), name="card_color_update"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<slug:uidb64>/<slug:token>', PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    
    path('access_authorization_data/', AccessAuthorizationDataView.as_view(), name="access_authorization_data"),
    path('access_authorization_add/', AccessAuthorizationAddView.as_view(), name = "access_authorization_add"),
    path('access_authorization_update/<int:id>/', AccessAuthorizationUpdateView.as_view(), name = "access_authorization_update"),
    path('access_authorization_delete/<str:list>/', AccessAuthorizationDeleteView.as_view(), name = "access_authorization_delete"),
    
    path('data_authorization_data/', DataAuthorizationDataView.as_view(), name="data_authorization_data"),
    path('data_authorization_add/', DataAuthorizationAddView.as_view(), name = "data_authorization_add"),
    path('data_authorization_update/<int:id>/', DataAuthorizationUpdateView.as_view(), name = "data_authorization_update"),
    path('data_authorization_delete/<str:list>/', DataAuthorizationDeleteView.as_view(), name = "data_authorization_delete"),
    
    path('user_authorization_data/', UserAuthorizationDataView.as_view(), name="user_authorization_data"),
    path('user_authorization_update/<int:id>/', UserAuthorizationUpdateView.as_view(), name = "user_authorization_update"),

    path('api/', include("user.api.urls")),
]

information/api/views.py
from django.core.validators import EMPTY_VALUES
from django.db.models import QuerySet
from django.http import JsonResponse
from rest_framework import generics
from rest_framework.filters import OrderingFilter
from rest_framework.views import APIView
from rest_framework_datatables.filters import DatatablesFilterBackend

from information.api.serializers import *
from information.models import Contact, Company, City, Country, Vessel
from information.scrapers import get_vessel_info


class QueryListAPIView(generics.ListAPIView):
    def get_queryset(self):
        if self.request.GET.get('format', None) == 'datatables':
            self.filter_backends = (OrderingFilter, DatatablesFilterBackend)
            return super().get_queryset()
        queryset = self.queryset

        # check the start index is integer
        try:
            start = self.request.GET.get('start')
            start = int(start) if start else None
        # else make it None
        except ValueError:
            start = None

        # check the end index is integer
        try:
            end = self.request.GET.get('end')
            end = int(end) if end else None
        # else make it None
        except ValueError:
            end = None

        # skip filters and sorting if they are not exists in the model to ensure security
        accepted_filters = {}
        # loop fields of the model
        for field in queryset.model._meta.get_fields():
            # if field exists in request, accept it
            if field.name in dict(self.request.GET):
                accepted_filters[field.name] = dict(self.request.GET)[field.name]
            # if field exists in sorting parameter's value, accept it

        filters = {}

        for key, value in accepted_filters.items():
            if any(val in value for val in EMPTY_VALUES):
                if queryset.model._meta.get_field(key).null:
                    filters[key + '__isnull'] = True
                else:
                    filters[key + '__exact'] = ''
            else:
                filters[key + '__in'] = value
        if isinstance(queryset, QuerySet):
            # Ensure queryset is re-evaluated on each request.
            queryset = queryset.all().filter(**filters)[start:end]
        return queryset

    @property
    def paginator(self):
        """
        The paginator instance associated with the view, or `None`.
        """
        if not hasattr(self, '_paginator'):
            if self.pagination_class is None:
                self._paginator = None
            elif self.request.GET.get('format', None) == 'datatables':
                self._paginator = self.pagination_class()
            else:
                self._paginator = None
        return self._paginator


class CountryList(QueryListAPIView):
    """
    Returns all countries
    Use GET parameters to filter queryset
    """
    queryset = Country.objects.all()
    serializer_class = CountryListSerializer
    filter_backends = [OrderingFilter]
    ordering_fields = '__all__'


class CityList(QueryListAPIView):
    """
    Returns all cities
    Use GET parameters to filter queryset
    """
    queryset = City.objects.all()
    serializer_class = CityListSerializer
    filter_backends = [OrderingFilter]
    ordering_fields = '__all__'


class CompanyList(QueryListAPIView):
    """
    Returns all companies
    Use GET parameters to filter queryset
    """
    custom_related_fields = ["company_group", "country", "city"]
    queryset = Company.objects.select_related(*custom_related_fields).all()
    serializer_class = CompanyListSerializer
    filter_backends = [OrderingFilter]
    ordering_fields = '__all__'


class CompanyCustomerList(QueryListAPIView):
    """
    Returns all companies those are customer
    Use GET parameters to filter queryset
    """
    custom_related_fields = ["company_group", "country", "city"]
    queryset = Company.objects.select_related(*custom_related_fields).filter(
        company_type__in=["Customer", "Customer & Supplier"])
    serializer_class = CompanyListSerializer
    filter_backends = [OrderingFilter]
    ordering_fields = '__all__'


class CompanySupplierList(QueryListAPIView):
    """
    Returns all companies those are supplier
    Use GET parameters to filter queryset
    """
    custom_related_fields = ["company_group", "country", "city"]
    queryset = Company.objects.select_related(*custom_related_fields).filter(
        company_type__in=["Supplier", "Customer & Supplier"])
    serializer_class = CompanyListSerializer
    filter_backends = [OrderingFilter]
    ordering_fields = '__all__'


class ContactList(QueryListAPIView):
    """
    Returns all contacts
    Use GET parameters to filter queryset
    """
    queryset = Contact.objects.prefetch_related("company").all()
    serializer_class = ContactListSerializer
    filter_backends = [OrderingFilter]
    ordering_fields = '__all__'


class VesselList(QueryListAPIView):
    """
    Returns all contacts
    Use GET parameters to filter queryset
    """
    custom_related_fields = ["manager_company", "owner_company"]
    queryset = Vessel.objects.select_related(*custom_related_fields).all()
    serializer_class = VesselListSerializer
    filter_backends = [OrderingFilter]
    ordering_fields = '__all__'


class CompanyAPI(generics.RetrieveDestroyAPIView):
    """
    Returns or deletes the company
    """
    custom_related_fields = ["company_group", "country", "city", "customer_representative", "key_account"]
    queryset = Company.objects.select_related(*custom_related_fields).all()
    serializer_class = CompanyDetailSerializer


class ContactAPI(generics.RetrieveUpdateDestroyAPIView):
    """
    Returns, delete or update the contact
    """
    queryset = Contact.objects.prefetch_related("company").all()
    serializer_class = ContactDetailSerializer


class VesselAPI(generics.RetrieveUpdateDestroyAPIView):
    """
    Returns, delete or update the vessel
    """
    queryset = Vessel.objects.prefetch_related("person_in_contacts").all()
    serializer_class = VesselDetailSerializer


class VesselDataFromOuter(APIView):
    """
    Retrieve vessel data from outer sources (only vesselfinder.com for now)
    """

    def get(self, request, imo):
        try:
            data = get_vessel_info(imo)
            return JsonResponse(data, safe=False)
        except TimeoutError as te:
            return JsonResponse({"detail": str(te)}, status=504)
        except TypeError as te:
            return JsonResponse({"detail": str(te)}, status=400)
        except ValueError as ve:
            return JsonResponse({"detail": str(ve)}, status=404)

templates/information/contact/contact_add.html
<!-- Layout eklemimizi sağlayan komut. -->
{% extends "layout.html" %}
<!-- Static dosyalarından yararlanmamız için. -->
{% load static i18n%}

<!-- Her sayfada sayfa özelinde dinamik olarak değişmesi gereken kısımlar burada tanımlanıyor. -->
{% block title %}{% trans 'Add Contact' %}{% endblock %}
{% block mainDirectory %}{% trans 'Information' %}{% endblock %}
{% block childDirectory %}{% trans 'Add Contact' %}{% endblock childDirectory %}
{% block href %}{% url 'information:contact_person_data' %}{% endblock %}
{% block mainRoute %}Contact{% endblock %}
{% block childRoute %}Add Contact{% endblock %}

{% block plugins %}
<script src="{% static 'lib/global_assets/js/plugins/forms/selects/select2.min.js' %}"></script>
<script src="{% static 'lib/global_assets/js/plugins/forms/selects/bootstrap_multiselect.js' %}"></script>
{% endblock %}

{% block demo_pages %}
<script src="{% static 'lib/global_assets/js/demo_pages/form_select2.js' %}"></script>
{% endblock %}


{% block content %}

<div class="col-lg-12">
    <div class="card">
        <div class="card-header">
            <div class="media flex-md-row mb-2">
                <a id="iconContact" class="align-self-md-start mr-3">
                    <img src="{% static 'images/icons/add-contact.svg' %}" class="rounded" width="44" height="44"
                        alt="">
                </a>
                <div class="media-body">
                    <h5 class="media-title font-weight-semibold">{% trans 'Add Contact' %}</h5>
                    <ul class="list-inline list-inline-dotted text-muted mb-0">
                        <li class="list-inline-item">Add new <u>contact</u> for company.</li>
                    </ul>
                </div>
                <div class="align-self-md-center actionButtons">
                </div>
            </div>
        </div>

        <div class="card-body">
            <form id="form" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    {% for field in contact_add_form %}
                    <div class="form-group col-md-4 col-lg-3">
                        <label>{{field.label}}</label>
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}
                </div>
                <fieldset class="card-body border-top w-100 text-right">
                    <button id="formSubmit" type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
                </fieldset>
            </form>
        </div>
    </div>
</div>


{% endblock %}
<!-- Content bloğu sonu -->
{% block javascript %}
<script type="module" src="{% static 'js/information/contact/contact_add.js' %}"></script>

{% endblock javascript %}

templates/information/contact/contact_detail.html
<!-- Layout eklemimizi sağlayan komut. -->
{% extends "layout.html" %}
<!-- Static dosyalarından yararlanmamız için. -->
{% load static i18n %}

<!-- Her sayfada sayfa özelinde dinamik olarak değişmesi gereken kısımlar burada tanımlanıyor. -->
{% block title %}{% trans 'Contact Detail' %}{% endblock %}
{% block mainDirectory %}{% trans 'Information' %}{% endblock %}
{% block childDirectory %}{% trans 'Contact Detail' %}{% endblock childDirectory %}
{% block href %}{% url 'information:contact_person_data' %}{% endblock %}
{% block mainRoute %}Contact{% endblock %}
{% block childRoute %}Contact Detail{% endblock %}

{% block plugins %}
<script src="{% static 'lib/global_assets/js/plugins/forms/selects/select2.min.js' %}"></script>
<script src="{% static 'lib/global_assets/js/plugins/forms/selects/bootstrap_multiselect.js' %}"></script>
<script src="{% static 'lib/global_assets/js/plugins/tables/datatables/datatables.min.js' %}"></script>
<script src="{% static 'lib/global_assets/js/plugins/tables/datatables/extensions/select.min.js' %}"></script>
<script src="{% static 'lib/global_assets/js/plugins/tables/datatables/extensions/jszip/jszip.min.js' %}"></script>
<script src="{% static 'lib/global_assets/js/plugins/tables/datatables/extensions/pdfmake/pdfmake.min.js' %}"></script>
<script
    src="{% static 'lib/global_assets/js/plugins/tables/datatables/extensions/pdfmake/vfs_fonts.min.js' %}"></script>
<script src="{% static 'lib/global_assets/js/plugins/tables/datatables/extensions/buttons.min.js' %}"></script>
<script src="{% static 'lib/global_assets/js/plugins/tables/datatables/extensions/row_reorder.min.js' %}"></script>
<script src="{% static 'lib/global_assets/js/plugins/tables/datatables/extensions/responsive.min.js' %}"></script>
{% endblock %}

{% block demo_pages %}
<script src="{% static 'lib/global_assets/js/demo_pages/form_select2.js' %}"></script>
{% endblock %}

{% block content %}

<!-- StyleSheet-->
<link rel="stylesheet" href="{% static 'css/information/contact/contact_detail.css' %}">
<!-- /StyleSheet End-->
<!-- Content bloğu -->
<div class="row">
    <!-- Company info -->
    <div class="col-xl-7">
        <div class="card company-info">
            <div class="card-header">
                <div class="media flex-md-row mb-2">
                    <a id="iconBuild" class="align-self-md-start mr-3">
                        <img src="{% static 'images/icons/details.svg' %}" class="rounded" width="44" height="44"
                            alt="">
                    </a>
                    <div class="media-body">
                        <h5 class="media-title font-weight-semibold">{% trans 'Contact Info' %}</h5>
                        <ul class="list-inline list-inline-dotted text-muted mb-0">
                            <li class="list-inline-item"><u>Contact</u> information.</li>
                        </ul>
                    </div>
                    {% block buttoneditremove %}
                        {% include "components/buttoneditremove.html" %}
                    {% endblock %}
                </div>
            </div>

            <div class="card-body p-0">
                <table class="table">
                    <thead>
                        <colgroup>
                            <col span="1" style="width: 30%;">
                            <col>
                        </colgroup>
                    </thead>
                    <tbody>
                        <tr>
                            <th class="text-muted">{% trans 'First Name' %}</th>
                            <td>{{contact.first_name}}</td>
                        </tr>
                        <tr>
                            <th class="text-muted">{% trans 'Last Name' %}</th>
                            <td>{{contact.last_name}}</td>
                        </tr>
                        <tr>
                            <th class="text-muted">{% trans 'Email Address' %}</th>
                            <td><a href="mailto:{{contact.email}}" target="_blank">{{contact.email}}</a></td>
                        </tr>
                        <tr>
                            <th class="text-muted">{% trans 'Birthday' %}</th>
                            <td>{{contact.birthday}}</td>
                        </tr>
                        <tr>
                            <th class="text-muted">{% trans 'Phone Number' %}</th>
                            <td><a href="tel:{{contact.phone_number}}" target="_blank">{{contact.phone_number}}</a></td>
                        </tr>
                        <tr>
                            <th class="text-muted">{% trans 'Office Address' %}</th>
                            <td>{{contact.office_address}}</td>
                        </tr>
                        <tr>
                            <th class="text-muted">{% trans 'Position' %}</th>
                            <td>{{contact.position}}</td>
                        </tr>
                        <tr>
                            <th class="text-muted">
                                {% trans 'Company' %}
                            </th>
                            <td class="p-0">
                                {% for company in contact.company.all %}
                                <div class="exit">
                                    <a href="{% url 'information:company_detail' company.id %}" target="_blank"
                                        class="font-weight-semibold letter-icon-title">
                                        {{ company }}</a>
                                    <!-- <div class="text-muted font-size-sm"><i>{{ contact }}</i></div> -->
                                </div>
                                {% endfor %}
                            </td>
                        </tr>
                        <tr>
                            <th class="text-muted">{% trans 'Default Person in Contact of' %}</th>
                            <td>
                                {% if contact.default_person_in_contact_of %}
                                <a href="{% url 'information:company_detail' contact.default_person_in_contact_of.id %}" target="_blank">
                                    {{contact.default_person_in_contact_of}}</a>
                                {% else %}
                                -
                                {% endif %}
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-xl-5">
        <div class="card">
            <div class="card-header">
                <div class="media flex-md-row mb-2">
                    <a id="iconBuild" class="align-self-md-start mr-3">
                        <img src="{% static 'images/icons/history.svg' %}" class="rounded" width="44" height="44"
                            alt="">
                    </a>
                    <div class="media-body">
                        <h5 class="media-title font-weight-semibold">{% trans 'Company History' %}</h5>
                        <ul class="list-inline list-inline-dotted text-muted mb-0">
                            <li class="list-inline-item"><u>Company</u> list for this contact.</li>
                        </ul>
                    </div>
                    <div class="actionButtonsForList">
                    </div>
                </div>
            </div>

            <div class="card-body p-0">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped">
                        <thead>
                            <colgroup>
                                <col span="1" style="width: 60%">
                            </colgroup>
                            <tr>
                                <th>{% trans 'Company' %}</th>
                                <th>{% trans 'Working Status' %}</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for history in contact.company_history.all %}
                            <tr>
                                <td>
                                    <a href="{% url 'information:company_detail' history.company.id %}" target="_blank">
                                        {{history.company}}
                                    </a>
                                </td>
                                <td>{{history.get_working_status_display}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- /Company info -->
</div>


{% endblock %}
<!-- Content bloğu sonu -->
{% block javascript %}
<script>
    let companyEditURL = "{% url 'information:contact_edit' contact.id %}"
    let companyDeleteURL = "{% url 'information:contact_delete' contact.id %}"
</script>
<script type="module" src="{% static 'js/information/contact/contact_detail.js' %}"></script>
{% endblock javascript %}

templates/information/contact/contact_person_data.html
<!-- Layout eklemimizi sağlayan komut. -->
{% extends "layout.html" %}
<!-- Static dosyalarından yararlanmamız için. -->
{% load static i18n%}
<!-- Her sayfada sayfa özelinde dinamik olarak değişmesi gereken kısımlar burada tanımlanıyor. -->
{% block title %}Contact Person Data{% endblock %}
{% block mainDirectory %}Information{% endblock %}
{% block childDirectory %}Contact Person Data{% endblock childDirectory %}
{% block href %}{% url 'user:dashboard' %}{% endblock %}
{% block mainRoute %}Contact Person Data{% endblock %}
{% block childRoute %}-{% endblock %}

{% block plugins %}
<script src="{% static 'lib/global_assets/js/plugins/tables/datatables/datatables.min.js' %}"></script>
<script src="{% static 'lib/global_assets/js/plugins/tables/datatables/extensions/select.min.js' %}"></script>
<script src="{% static 'lib/global_assets/js/plugins/tables/datatables/extensions/jszip/jszip.min.js' %}"></script>
<script src="{% static 'lib/global_assets/js/plugins/tables/datatables/extensions/pdfmake/pdfmake.min.js' %}"></script>
<script
    src="{% static 'lib/global_assets/js/plugins/tables/datatables/extensions/pdfmake/vfs_fonts.min.js' %}"></script>
<script src="{% static 'lib/global_assets/js/plugins/tables/datatables/extensions/buttons.min.js' %}"></script>
<script src="{% static 'lib/global_assets/js/plugins/tables/datatables/extensions/row_reorder.min.js' %}"></script>
<script src="{% static 'lib/global_assets/js/plugins/tables/datatables/extensions/responsive.min.js' %}"></script>
{% endblock %}

{% block demo_pages %}
{% if request.user.profile.theme == 'light' %}

{% else %}

{% endif %}
{% endblock %}

{% block content %}
{% url 'information:contact_add' as add_url %}
<!-- StyleSheet-->
<link rel="stylesheet" href="{% static 'css/information/customer/customer_data/customer_data.css' %}">
<!-- /StyleSheet End-->
<!-- Basic initialization -->
<div class="card">
    <div class="card-header header-elements-inline">
        <div class="header-elements">
            <h5 class="m-0">Contact Person Table</h5>
        </div>
        {% block buttonaddinfo %}
        {% include "components/buttonaddinfo.html" with add_url=add_url|add:"?next="|add:request.path %}
        {% endblock %}
    </div>

    <table id="contactDatatable" class="table table-striped table-hover table-bordered dataTable no-footer">
        <thead>
            <tr>
                <th>ID</th>
                <th>No.</th>
                <th>Name</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Position</th>
                <th>Phone Number</th>
                <th>E-mail</th>
            </tr>
        </thead>
        <tbody id="tbody">
        </tbody>
    </table>
</div>
<!-- /Basic initialization -->

{% endblock %}
{% block javascript %}
<script>
    const contact_add_url = "{% url 'information:contact_add' %}";
    const contacts_api = "{% url 'information:contacts_api' %}?format=datatables";
    const contact_api = "{% url 'information:contact_api' 0 %}";

</script>
<script type="module" src="{% static 'js/information/contact/contact_data.js' %}"></script>
{% endblock javascript %}