card/api/urls.py
from django.urls import path, include
from rest_framework import routers

from card.api.views import *

router = routers.DefaultRouter()
#router.register(r'companies', CompanyList, "companies_api")
router.register(r'currents', CurrentList, "currents_api")
router.register(r'banks', BankList, "banks_api")
router.register(r'vessels', VesselList, "vessels_api")
router.register(r'engine_parts', EnginePartList, "engine_parts_api")
router.register(r'owners', OwnerList, "owners_api")
router.register(r'billing_in_vessels', BillingInVesselList, "billing_in_vessels_api")
router.register(r'billings', BillingList, "billings_api")
router.register(r'currencies', CurrencyList, "currencies_api")

urlpatterns = [
    path('',include(router.urls)),
    path('countries', CountryList.as_view(), name="countries_api"),
    path('cities', CityList.as_view(), name="cities_api"),
    path('companies', CompanyList.as_view(), name="companies_api"),
    path('persons', PersonList.as_view(), name="persons_api"),
    path('vessel_histories/<int:id>/', VesselHistoryList.as_view(), name="vessel_histories_api"),
]

card/urls.py
from django.urls import path, include

from . import views

from .views.company_views import *
from .views.vessel_views import *
from .views.billing_views import *

app_name = "card"

urlpatterns = [
    path('card_data/', CardDataView.as_view(), name="card_data"),
    path('vessel_data/', VesselDataView.as_view(), name="vessel_data"),
    
    path('company_add/', CompanyAddView.as_view(), name = "company_add"),
    path('company_update/<int:id>/', CompanyUpdateView.as_view(), name = "company_update"),
    path('company_delete/<str:list>/', CompanyDeleteView.as_view(), name = "company_delete"),
    path('company_filter_excel/', CompanyFilterExcelView.as_view(), name = "company_filter_excel"),
    path('company_export_excel', CompanyExportExcelView.as_view(), name = "company_export_excel"),
    path('company_download_excel/', CompanyDownloadExcelView.as_view(), name = "company_download_excel"),
    path('get_updates_from_mikro/c_<int:id>_hk_<str:hesapKodu>/', CompanyUpdateFromMikroView.as_view(), name = "get_updates_from_mikro"),
    path('send_updates_to_mikro/c_<int:id>_hk_<str:hesapKodu>/', CompanyUpdateToMikroView.as_view(), name = "send_updates_to_mikro"),
    path('match_with_mikro/c_<int:id>_hk_<str:hesapKodu>/', CompanyMatchWithMikroView.as_view(), name = "match_with_mikro"),
    path('unmatch_with_mikro/c_<int:id>/', CompanyUnmatchWithMikroView.as_view(), name = "unmatch_with_mikro"),
    path('company_create_mikro/c_<int:id>_hk_<str:hesapKodu>/', CompanyCreateMikroView.as_view(), name = "company_create_mikro"),
    
    path('vessel_add/', VesselAddView.as_view(), name = "vessel_add"),
    path('vessel_update/<int:id>/', VesselUpdateView.as_view(), name = "vessel_update"),
    path('vessel_update_modal/<int:id>/', VesselUpdateModalView.as_view(), name = "vessel_update_modal"),
    path('vessel_delete/<str:list>/', VesselDeleteView.as_view(), name = "vessel_delete"),
    
    path('engine_part_add_in_detail/v_<int:id>/', EnginePartInDetailAddView.as_view(), name = "engine_part_add_in_detail"),
    path('engine_part_delete/<str:list>', EnginePartDeleteView.as_view(), name = "engine_part_delete"),
    
    path('person_add_in_company/', PersonAddInCompanyView.as_view(), name = "person_add_in_company"),
    path('person_add_in_vessel/', PersonAddInVesselView.as_view(), name = "person_add_in_vessel"),
    path('person_add_in_detail_vessel/', PersonInDetailVesselAddView.as_view(), name = "person_add_in_detail_vessel"),
    path('person_add_in_detail_company/', PersonInDetailCompanyAddView.as_view(), name = "person_add_in_detail_company"),
    path('person_update_in_vessel/<int:id>/', PersonUpdateInVesselView.as_view(), name = "person_update_in_vessel"),
    path('person_update_in_company/<int:id>/', PersonUpdateInCompanyView.as_view(), name = "person_update_in_company"),
    path('person_delete/<str:list>', PersonDeleteView.as_view(), name = "person_delete"),
    
    path('bank_add_in_detail_company/c_<int:id>/', BankInDetailCompanyAddView.as_view(), name = "bank_add_in_detail_company"),
    path('bank_update_in_company/<int:id>/', BankUpdateInCompanyView.as_view(), name = "bank_update_in_company"),
    path('bank_delete/<str:list>', BankDeleteView.as_view(), name = "bank_delete"),
    
    path('owner_add_in_vessel/', OwnerAddView.as_view(), name = "owner_add_in_vessel"),
    path('owner_add_in_detail/v_<int:id>/', OwnerInDetailAddView.as_view(), name = "owner_add_in_detail"),
    path('owner_delete/<str:list>', OwnerDeleteView.as_view(), name = "owner_delete"),
    
    path('billing_data/', BillingDataView.as_view(), name="billing_data"),
    path('billing_update/<int:id>/', BillingUpdateView.as_view(), name = "billing_update"),
    path('billing_add_in_detail/v_<int:id>/', BillingInDetailAddView.as_view(), name = "billing_add_in_detail"),
    path('billing_delete/<str:list>', BillingDeleteView.as_view(), name = "billing_delete"),
    path('billing_match_with_mikro/b_<int:id>_hk_<str:hesapKodu>/', BillingMatchWithMikroView.as_view(), name = "billing_match_with_mikro"),
    path('billing_unmatch_with_mikro/b_<int:id>/', BillingUnmatchWithMikroView.as_view(), name = "billing_unmatch_with_mikro"),
    path('billing_get_updates_from_mikro/c_<int:id>_hk_<str:hesapKodu>/', BillingUpdateFromMikroView.as_view(), name = "billing_get_updates_from_mikro"),
    path('billing_send_updates_to_mikro/c_<int:id>_hk_<str:hesapKodu>/', BillingUpdateToMikroView.as_view(), name = "billing_send_updates_to_mikro"),
    path('billing_create_mikro/c_<int:id>_hk_<str:hesapKodu>/', BillingCreateMikroView.as_view(), name = "billing_create_mikro"),
    
    path('company_logo/<int:id>/', CompanyLogoView.as_view(), name = "company-logo"),
    path('get-cities/', get_cities, name = "get-cities"),
    
    path('api/', include("card.api.urls")),
]

hr/urls.py
from django.urls import path, include

from .views import *

app_name = "hr"

urlpatterns = [
    path('the_company/', TheCompanyDetailView.as_view(), name="the_company_detail"),
    path('the_company_edit/', TheCompanyEditView.as_view(), name="the_company_edit"),
    path('the_company/bank_account_delete/<int:bank_account_id>', BankAccountDeleteView.as_view(),
         name="bank_account_delete"),

    path('user_data/', UserDataView.as_view(), name="user_data"),
    path('user_add/', UserAddView.as_view(), name="user_add"),
    path('user_update/<int:id>/', UserUpdateView.as_view(), name = "user_update"),
    path('user_delete/<str:list>', UserDeleteView.as_view(), name="user_delete"),
    path('user_cv_pdf/<int:id>/', UserCVPdfView.as_view(), name = "user_cv_pdf"),
    path('user_nda_pdf/<int:id>/', UserNDAPdfView.as_view(), name = "user_nda_pdf"),
    
    path('user_edit/<int:user_id>', UserEditView.as_view(), name="user_edit"),
    path('user/<int:user_id>', UserDetailView.as_view(), name="user_detail"),
    path('user/certification/<int:profile_id>', CertificationAddView.as_view(),name="certificatiob_add"),

    path('employee_type_add/', EmployeeTypeAddView.as_view(), name="employee_type_add"),
    path('employee_type/<int:employee_type_id>', EmployeeTypeDetailView.as_view(), name="employee_type_detail"),
    path('employee_type_edit/<int:employee_type_id>', EmployeeTypeEditView.as_view(), name="employee_type_edit"),
    path('employee_type_delete/<int:employee_type_id>', EmployeeTypeDeleteView.as_view(), name="employee_type_delete"),
    path('employee_type_data/', EmployeeTypeDataView.as_view(), name="employee_type_data"),

    path('team_add/', TeamAddView.as_view(), name="team_add"),
    path('team/<int:team_id>', TeamDetailView.as_view(), name="team_detail"),
    path('team_update/<int:id>/', TeamUpdateView.as_view(), name = "team_update"),
    path('team_edit/<int:team_id>', TeamEditView.as_view(), name="team_edit"),
    path('team_delete/<str:list>', TeamDeleteView.as_view(), name="team_delete"),
    path('team_data/', TeamDataView.as_view(), name="team_data"),

    path('department_add/', DepartmentAddView.as_view(), name="department_add"),
    path('department/<int:department_id>', DepartmentDetailView.as_view(), name="department_detail"),
    path('department_update/<int:id>/', DepartmentUpdateView.as_view(), name = "department_update"),
    path('department_edit/<int:department_id>', DepartmentEditView.as_view(), name="department_edit"),
    path('department_delete/<str:list>', DepartmentDeleteView.as_view(), name="department_delete"),
    path('department_data/', DepartmentDataView.as_view(), name="department_data"),
    
    path('education_add_in_user/', EducationAddView.as_view(), name = "education_add_in_user"),
    path('education_add_in_detail/u_<int:id>/', EducationInDetailAddView.as_view(), name = "education_add_in_detail"),
    path('education_delete/<str:list>', EducationDeleteView.as_view(), name = "education_delete"),
    
    path('additional_payment_add_in_detail/u_<int:id>/', AdditionalPaymentInDetailAddView.as_view(), name = "additional_payment_add_in_detail"),
    
    path('organization_chart_data/', OrganizationChartDataView.as_view(), name="organization_chart_data"),

    path('record/<int:record_id>', RecordDetailView.as_view(), name="record_detail"),
    path('record_data/', RecordDataView.as_view(), name="record_data"),

    path('api/', include("hr.api.urls")),
]

templates/card/company/companies.html
{% load static %}
{% include 'includes/control/htmx_control.html' %}

{% block body %}
{% load crispy_forms_tags %}

<style>
    * html body{font-family: "Roboto", sans-serif!important;}
    .home-section{overflow:hidden!important;}
    
</style>

<li class="nav-item" role="presentation" id="navTag-{{elementTag}}" style="display:none;flex: 0 0 auto;">
    <a class="nav-link mainNavLink position-relative border border-1 rounded-0 border-secondary-subtle" id="navTagLink-{{elementTag}}" data-mdb-pill-init data-mdb-pill-init data-mdb-toggle="tab" href="#tabPane-{{elementTag}}" role="tab" aria-controls="tabPane-{{elementTag}}" aria-selected="true">
        {% comment %} <i class="fa-solid fa-building me-2"></i> {% endcomment %}
        {{tag}}
        <button class="btn btn-tertiary position-absolute top-20 translate-middle badge p-1" href="#" id="removeNav-{{elementTag}}" style="margin-left: 15%;">
            <i class="fa-solid fa-xmark" style="font-size:0.75rem;"></i>
        </button>
    </a>
</li>

<div class="tab-pane mainTabPane fade" id="tabPane-{{elementTag}}" role="tabpanel" aria-labelledby="navTagLink-{{elementTag}}">

    <!-- Tabs navs Sub-->
    <ul class="nav nav-pills sortable-list d-flex" style="background-color: #f1f2f7" id="tabNavSub-{{elementTag}}" data-mdb-sortable="sortable" role="tablist" style="margin-bottom: 0 !important;">
        <li class="nav-item" role="presentation" id="navTag-{{elementTag}}-table">
            <a class="nav-link mainNavLinkSub-{{elementTag}} active border border-1 rounded-0 border-secondary-subtle" id="navTagLink-{{elementTag}}-table" data-mdb-pill-init data-mdb-pill-init data-mdb-toggle="tab" href="#tabPane-{{elementTag}}-table" role="tab" aria-controls="tabPane-{{elementTag}}-table" aria-selected="true" style="font-size:9px;padding:10px 25px 10px 25px;margin: 0px!important;">
                List
            </a>
        </li>
    </ul>
    <!-- Tabs navs Sub-->

    <!-- Tabs content -->
    <div class="tab-content" id="tabContSub-{{elementTag}}" hx-target="this">

        <div class="tab-pane mainTabPaneSub-{{elementTag}} fade show active" id="tabPane-{{elementTag}}-table" role="tabpanel" aria-labelledby="navTagLink-{{elementTag}}-table">

            <div class="globalBoxes">
                <div class="box tableBox tableBox-{{elementTag}}" style="transition: all 1s ease;">
                    {% comment %} <div class="topButtonBox">
                        <a class="tableTopButtons" hx-get="{% url 'card:company_add' %}" hx-target="#addUpdateDataDialogXl" style=""><i class="fa-solid fa-plus"></i></a>
                        <a class="deleteData tableTopButtons" href="#" style=""><i class="fa-solid fa-trash"></i></a>
                        <a class="tableTopButtons" href="#" style=""><i class="fa-solid fa-print"></i></a>
                        <a class="tableTopButtons" href="{% url 'card:company_bulk_add_excel' %}" style=""><i class="fa-solid fa-file-arrow-down"></i></a>
                        <a class="tableTopButtons" hx-get="{% url 'card:company_bulk_add' %}" hx-target="#addUpdateDataDialog-r" style=""><i class="fa-solid fa-file-arrow-up"></i></a>
                    </div> {% endcomment %}
                    <table id="table-{{elementTag}}" class="table table-striped table-hover table-bordered dataTable no-footer" data-mdb-max-height="460" data-mdb-fixed-header="true" style="width:100%;transition: all 1s ease;">
                        <thead>
                            <tr>
                                <th>Select</th>
                                <th>Line</th>
                                <th>ID</th>
                                <th>Company Name</th>
                                <th>Cari Kod</th>
                                <th>Type</th>
                                <th>Country</th>
                                <th>City</th>
                                <th>Phone</th>
                                <th>Email</th>
                                <th>Company No</th>
                                <th>Vat Office</th>
                                <th>Vat No</th>
                            </tr>
                        </thead>
                        <tbody id="tbody">
                           
                        </tbody>
                    </table>
                </div>

                <div id="addFormBlock-{{elementTag}}" hx-target="this" class="box addForm-{{elementTag}}" style="box-shadow:none;padding-top:65px;transition: all 1s ease;">
                    
                </div>
                
            </div>

        </div>
    </div>

</div>



<script>

    var elementTag = "{{elementTag}}";
    var elementTagSub = "{{elementTagSub}}";
    var elementTagId = "table";
    var pageUrl = "/card/card_data/"

    

    


    {% comment %} var tabs1 = $("#homeContent").tabs();
	tabs1.find( ".ui-tabs-nav" ).sortable({
		axis: "x",
		stop: function() {
			tabs1.tabs( "refresh" );
		}
	}); {% endcomment %}
    {% comment %} $.busyLoadSetup({ animation: "slide", background: "rgba(255, 152, 0, 0.86)" }); 
    $("#spinnerButton").click(function(){
        $(".tableBox-{{elementTag}}").busyLoad("show", {
            //background: "rgba(255, 152, 0, 0.86)",
            spinner: "pulsar",
            maxSize: "150px",
            minSize: "150px",
            text: "LOADING ...",
            background: "rgba(165, 42, 42, 0.75)",
            color: "rgb(165, 42, 42)",
            textColor: "#fff"
        });
    }); {% endcomment %}
    

</script>

{% endblock body %}

{% block javascript %}

<script src="{% static 'js/card/company/list.js' %}"></script>

{% endblock javascript %}

templates/card/company/company-logo.html
<div class="modal-body">
    <div class="mb-3">
    <img src="{{ src }}" style="max-width: 100%;">
    </div>
</div>

templates/card/company/company_bulk_add.html
{% include 'includes/control/htmx_control.html' %}

<form hx-post="{{ request.path }}" class="modal-content" enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    <div class="modal-header">
        <h5 class="modal-title">{{tag}}</h5>
    </div>
    <div class="modal-body">
        <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label"></label>
        {{form.file}}
        </div>
    <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Cancel</button>
        <button class="btn btn-danger" type="submit">Load</button>
    </div>
</form>

templates/card/company/company_delete.html
{% include 'includes/control/htmx_control.html' %}

<form hx-post="{{ request.path }}" class="modal-content form-container border" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="modal-header">
        <h5 class="modal-title">Delete selected companies?</h5>
    </div>
    <div class="modal-footer shadow-5-strong" style="padding: 10px;">
        <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Cancel</button>
        <button class="btn btn-danger" type="submit" name="deleteCompany">Delete</button>
    </div>
</form>

templates/card/company/company_excel.html
{% load static %}
{% include 'includes/control/htmx_control.html' %}

<form hx-post="{{request.path}}" class="modal-content form-container border" id="form-{{elementTag}}-" enctype="multipart/form-data" style="height:auto!important">
    {% csrf_token %}
    <div class="modal-header">
        <h5 class="modal-title">Export Company List</h5>
    </div>
    <div class="modal-body">
        <div class="row">

            <div class="col-md-4">
                <div class="row p-2 pt-0">
                    <div class="col-md-12 bg-red-esms text-white">
                        Filter Role
                    </div>
                </div>
                <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" role="switch" id="cSwitchCompany" checked />
                    <label for="cSwitchCompany" class="form-check-label me-4" name="cSwitchCompany-name">Customer</label>
                </div>
                <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" role="switch" id="sSwitchCompany" checked />
                    <label for="sSwitchCompany" class="form-check-label me-4" name="sSwitchCompany-name">Supplier</label>
                </div>
            </div>

            <div class="col-md-8">
                <div class="row p-2 pt-0">
                    <div class="col-md-12 bg-red-esms text-white">
                        Filter Location
                    </div>
                </div>
        
                <div class="row">
                    <div class="col-md-6 p-2">
                        <div class="form-outline">
                            <select class="form-control form-control-sm form-select select" id="coSelectCompany" data-mdb-size="sm">
                                <option value="0">-----</option>
                                {% for country in countries %}
                                    <option value="{{ country.id }}">{{ country.international_formal_name }}</option>
                                {% endfor %}
                            </select>
                            <label for="coSelectCompany" class="form-label select-label">Country</label>
                        </div>
                    </div>
                    <div class="col-md-6 p-2">
                        <div class="form-outline">
                            <select class="form-control form-control-sm form-select select" id="ciSelectCompany" data-mdb-size="sm">
                                <option value="0">-----</option>
                            </select>
                            <label for="ciSelectCompany" class="form-label select-label">City</label>
                        </div>
                    </div>
                    <span class="p-2">Note: If any country or city is not selected, all will be exported.</span>
                </div>
            </div>

        </div>
        

        
    </div>
    <div class="modal-footer shadow-5-strong" style="padding: 10px;">
        <div class="col-md-8 me-auto">
            <div class="row">
                <div class="col-md-10 d-flex" style="align-items:center;">
                    <div class="progress w-100 m-0 d-none" id="exportProgressBarCompanyBlock">
                        <div id="exportProgressBarCompany" class="progress-bar bg-danger" role="progressbar" style="width: 0%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                </div>
                <div class="col-md-1 d-flex" style="align-items:center;">
                    <span class="d-none" id="percentCountCompany">0%</span>
                </div>
                <div class="col-md-1">
                    <button class="btn btn-danger bg-blue-esms me-auto d-none" type="button" id="downloadCompanyExcel">Download</button>
                </div>
            </div>
        </div>
        <button class="btn btn-secondary bg-red-esms text-white" type="button" data-bs-dismiss="modal">Cancel</button>
        <button class="btn btn-danger bg-blue-esms" type="button" id="exportCompanyExcel">Export</button>
    </div>
</form>

<script>
    var elementTag = "{{elementTag}}";
    var elementTagSub = "{{elementTagSub}}";
    var sessionKey = "{{sessionKey}}";
    var pageUrl = "/card/company_excel/";
    var user = "{{user.id}}";

    //new mdb.Select($("#coSelectCompany"));

    //$("#table-purchaseOrderCompanyExcel").DataTable().columns.adjust();

    $('#coSelectCompany').on('change', function() {
        var countryInformId = $(this).val();
        $.ajax({
            url: '/card/api/cities',
            data: {'country': countryInformId},
            dataType: 'json',
            success: function(data) {
                $('#ciSelectCompany').empty();
                $('#ciSelectCompany').append($('<option>').val(0).text("-----"));
                $.each(data, function(i, city) {
                    $('#ciSelectCompany').append($('<option>').val(city.id).text(city.name));
                });
                $("#ciSelectCompany").trigger("change");
            }
        });
    });

    $("#exportCompanyExcel").on("click", function(){
        $(this).prop("disabled",true);

        $("#exportProgressBarCompanyBlock").removeClass("d-none");
        $("#percentCountCompany").removeClass("d-none");

        var cSwitchCompany = $("#cSwitchCompany").is(':checked');
        var sSwitchCompany = $("#sSwitchCompany").is(':checked');
        
        let selectedCountry = $("#coSelectCompany").val();
        let selectedCity = $("#ciSelectCompany").val();

        //window.location.href = "/sale/purchase_order_download_excel?po=" + orderConfirmationSwitchCompany + "&ot=" + orderTrackingSwitchCompany + "&i=" + invoicedSwitchCompany + "&start=" + $('#startDate').val() + "&end=" + $('#endDate').val() + "&c=" + selectedCompanies;
        //addUpdateDataModalXl.hide();

        htmx.ajax("POST", "/card/company_export_excel?c=" + cSwitchCompany +
                                                    "&s=" + sSwitchCompany +
                                                    "&co=" + selectedCountry +
                                                    "&ci=" + selectedCity
        );

        

    });

</script>

{% block javascript %}
<script src="{% static 'js/card/company/filter.js' %}"></script>
{% endblock javascript %}

templates/card/company/create_mikro_company.html
{% load static %}
{% include 'includes/control/htmx_control.html' %}

<form hx-post="{{ request.path }}" class="modal-content form-container border" id="form-{{elementTag}}-{{elementTagId}}-create" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="modal-header">
        <h5 class="modal-title">Create new account card in Mikro</h5>
    </div>
    <div class="modal-footer shadow-5-strong" style="padding: 10px;">
        <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Cancel</button>
        <button class="btn btn-danger" type="submit">Create</button>
    </div>
</form>

<script>
    var elementTag = "{{elementTag}}";
    var elementTagSub = "{{elementTagSub}}";
    var elementTagId = "{{elementTagId}}";
    var companyId = "{{company.id}}";
    var sessionKey = "{{sessionKey}}";
    var pageUrl = "/card/create_mikro_company/c_{{company.id}}_hk_{{cariKod}}";
    var user = "{{user.id}}";

    $("#form-" + elementTag +  "-" + elementTagId + "-create").submit(function (event) {
        //spinner başlatır
        $("body").busyLoad("show", {
            animation: false,
            spinner: "pulsar",
            maxSize: "150px",
            minSize: "150px",
            text: "Loading ...",
            background: "rgba(69, 83, 89, 0.6)",
            color: "#455359",
            textColor: "#fff"
        });

        event.preventDefault();

        addUpdateDataModal.hide();

    });
</script>

{% block javascript %}




{% endblock javascript %}

templates/card/company/get_updates_from_mikro.html
{% load static %}
{% include 'includes/control/htmx_control.html' %}

<form hx-post="{{ request.path }}" class="modal-content form-container border" id="form-{{elementTag}}-{{elementTagId}}-fromUpdate" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="modal-header">
        <h5 class="modal-title">Get last updates from Mikro?</h5>
    </div>
    <div class="modal-footer shadow-5-strong" style="padding: 10px;">
        <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Cancel</button>
        <button class="btn btn-danger" type="submit">Update</button>
    </div>
</form>

<script>
    var elementTag = "{{elementTag}}";
    var elementTagSub = "{{elementTagSub}}";
    var elementTagId = "{{elementTagId}}";
    var sessionKey = "{{sessionKey}}";
    var user = "{{user.id}}";

    $("#form-" + elementTag +  "-" + elementTagId + "-fromUpdate").submit(function (event) {
        //spinner başlatır
        $("body").busyLoad("show", {
            animation: false,
            spinner: "pulsar",
            maxSize: "150px",
            minSize: "150px",
            text: "Loading ...",
            background: "rgba(69, 83, 89, 0.6)",
            color: "#455359",
            textColor: "#fff"
        });

        event.preventDefault();

        addUpdateDataModal.hide();

    });
</script>

{% block javascript %}




{% endblock javascript %}

templates/card/company/send_updates_to_mikro.html
{% load static %}
{% include 'includes/control/htmx_control.html' %}

<form hx-post="{{ request.path }}" class="modal-content form-container border" id="form-{{elementTag}}-{{elementTagId}}-toUpdate" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="modal-header">
        <h5 class="modal-title">Send last updates to Mikro?</h5>
    </div>
    <div class="modal-footer shadow-5-strong" style="padding: 10px;">
        <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Cancel</button>
        <button class="btn btn-danger" type="submit">Update</button>
    </div>
</form>

<script>
    var elementTag = "{{elementTag}}";
    var elementTagSub = "{{elementTagSub}}";
    var elementTagId = "{{elementTagId}}";
    var companyId = "{{company.id}}";
    var sessionKey = "{{sessionKey}}";
    var pageUrl = "/card/send_updates_to_mikro/c_{{company.id}}_hk_{{cariKod}}";
    var user = "{{user.id}}";

    $("#form-" + elementTag +  "-" + elementTagId + "-toUpdate").submit(function (event) {
        //spinner başlatır
        $("body").busyLoad("show", {
            animation: false,
            spinner: "pulsar",
            maxSize: "150px",
            minSize: "150px",
            text: "Loading ...",
            background: "rgba(69, 83, 89, 0.6)",
            color: "#455359",
            textColor: "#fff"
        });

        event.preventDefault();

        addUpdateDataModal.hide();

    });
</script>

{% block javascript %}




{% endblock javascript %}

templates/card/company/unmatch_with_mikro.html
{% load static %}
{% include 'includes/control/htmx_control.html' %}

<form hx-post="{{ request.path }}" class="modal-content form-container border" id="form-{{elementTag}}-{{elementTagId}}-withUnmatch" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="modal-header">
        <h5 class="modal-title">Unmatch with current in Mikro?</h5>
    </div>
    <div class="modal-footer shadow-5-strong" style="padding: 10px;">
        <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Cancel</button>
        <button class="btn btn-danger" type="submit">Unmatch</button>
    </div>
</form>

<script>
    var elementTag = "{{elementTag}}";
    var elementTagSub = "{{elementTagSub}}";
    var elementTagId = "{{elementTagId}}";
    var companyId = "{{company.id}}";
    var sessionKey = "{{sessionKey}}";
    var pageUrl = "/card/unmatch_with_mikro/c_{{company.id}}";
    var user = "{{user.id}}";

    $("#form-" + elementTag +  "-" + elementTagId + "-withUnmatch").submit(function (event) {
        //spinner başlatır
        $("body").busyLoad("show", {
            animation: false,
            spinner: "pulsar",
            maxSize: "150px",
            minSize: "150px",
            text: "Loading ...",
            background: "rgba(69, 83, 89, 0.6)",
            color: "#455359",
            textColor: "#fff"
        });

        event.preventDefault();

        addUpdateDataModal.hide();

    });
</script>

{% block javascript %}




{% endblock javascript %}